/**
 * LocalStorageCollection — Collection backed by a Web Storage object.
 *
 * Key namespacing scheme: `<clientId>:<collectionName>:<docKey>`
 *
 * All documents are stored as JSON strings. The clientId is generated at
 * LocalStorageClient construction time, preventing cross-client contamination
 * when multiple jsnosqlc clients share the same storage backend.
 *
 * find() iterates all storage keys with the matching prefix and applies
 * MemoryFilterEvaluator to each parsed document.
 *
 * Supported operations: get, store, delete, insert, update, find
 */
import { Collection, Cursor } from '@alt-javascript/jsnosqlc-core';
import MemoryFilterEvaluator from './MemoryFilterEvaluator.js';

let _idCounter = 0;
function generateId() {
  return `ls_${Date.now().toString(16)}_${(++_idCounter).toString(16)}_${Math.random().toString(16).slice(2, 8)}`;
}

export default class LocalStorageCollection extends Collection {
  /**
   * @param {import('@alt-javascript/jsnosqlc-core').Client} client
   * @param {string} name — collection name
   * @param {string} clientId — unique id generated by LocalStorageClient
   * @param {Storage} storage — Web Storage object (localStorage, sessionStorage, or MockStorage)
   */
  constructor(client, name, clientId, storage) {
    super(client, name);
    this._clientId = clientId;
    this._storage = storage;
    // Namespace prefix: all keys for this collection look like "<clientId>:<name>:"
    this._prefix = `${clientId}:${name}:`;
  }

  /** Build a namespaced storage key from a document key. */
  _nsKey(key) {
    return `${this._prefix}${key}`;
  }

  async _get(key) {
    const raw = this._storage.getItem(this._nsKey(key));
    if (raw === null) return null;
    return JSON.parse(raw);
  }

  async _store(key, doc) {
    this._storage.setItem(this._nsKey(key), JSON.stringify(doc));
  }

  async _delete(key) {
    this._storage.removeItem(this._nsKey(key));
  }

  async _insert(doc) {
    const id = generateId();
    this._storage.setItem(this._nsKey(id), JSON.stringify({ ...doc, _id: id }));
    return id;
  }

  async _update(key, patch) {
    const existing = await this._get(key);
    if (existing === null) {
      throw new Error(`Document not found for key: ${key}`);
    }
    this._storage.setItem(this._nsKey(key), JSON.stringify({ ...existing, ...patch }));
  }

  async _find(ast) {
    const results = [];
    const prefixLen = this._prefix.length;

    for (let i = 0; i < this._storage.length; i++) {
      const rawKey = this._storage.key(i);
      if (rawKey !== null && rawKey.startsWith(this._prefix)) {
        const raw = this._storage.getItem(rawKey);
        if (raw !== null) {
          const doc = JSON.parse(raw);
          if (MemoryFilterEvaluator.matches(doc, ast)) {
            results.push(doc);
          }
        }
      }
    }

    return new Cursor(results);
  }
}
